# Generated by Django 3.0.4 on 2020-03-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(default='pictures/default.jpg', upload_to='pictures/%y/%m/%d/'),
        ),
    ]
