# Generated by Django 3.0.4 on 2020-03-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_message', '0002_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(default='pictures/default.jpg', max_length=255, upload_to='pictures/%y/%m/%d/'),
        ),
    ]
